name: learn-github-actions
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: sudo apt install python  
      - run: python main.py
        env:
            first_name : ${{FNAME}}
            last_name : ${{LNAME}}